const nff = require('../')
const t = require('tap')
t.equal(nff('/a/b/c/@foo/bar'), '@foo/bar')
t.equal(nff('/a/b/c/foo/bar'), 'bar')
t.equal(nff(null), false)
t.equal(nff('/'), '/', 'root directories return their path as name')
t.equal(nff('C:\\'), 'C:\\', 'root directories return their path as name')
